# Generated by Django 5.2.17 on 2026-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stone",
            options={
                "ordering": ["order", "label"],
                "permissions": [("transition_stone", "Can change a stone's status")],
            },
        ),
    ]
