# Generated by Django 5.2.17 on 2026-08-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_stone_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stone",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="stone_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of stones the customer submitted."
            ),
        ),
    ]
