# Generated by Django 5.2.17 on 2026-09-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_stone_quantity_order_stone_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stone",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="weight_unit",
            field=models.CharField(
                choices=[("carat", "Carat"), ("gram", "Gram")],
                default="carat",
                max_length=10,
            ),
        ),
    ]
