# Generated by Django 5.2.17 on 2026-09-02 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_stone_weight_alter_stone_weight_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_active_order_reference_no",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="reference_no",
            new_name="reference_number",
        ),
        migrations.AlterField(
            model_name="statushistory",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("received", "Received"),
                    ("under_identification", "Under identification"),
                    ("billed", "Billed"),
                    ("paid", "Paid"),
                    ("certified", "Certified"),
                    ("ready_for_collection", "Ready for collection"),
                    ("collected", "Collected"),
                    ("on_hold", "On hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("under_identification", "Under identification"),
                    ("billed", "Billed"),
                    ("paid", "Paid"),
                    ("certified", "Certified"),
                    ("ready_for_collection", "Ready for collection"),
                    ("collected", "Collected"),
                    ("on_hold", "On hold"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("under_identification", "Under identification"),
                    ("billed", "Billed"),
                    ("paid", "Paid"),
                    ("certified", "Certified"),
                    ("ready_for_collection", "Ready for collection"),
                    ("collected", "Collected"),
                    ("on_hold", "On hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="received",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("reference_number",),
                name="unique_active_order_reference_number",
            ),
        ),
    ]
