# Generated by Django 5.2.17 on 2026-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["stone", "started_at"],
                "permissions": [("record_qa", "Can record production QA")],
            },
        ),
    ]
