# Generated by Django 5.2.17 on 2026-08-28 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentificationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("report_number", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("colorless", "Colorless"),
                            ("white", "White"),
                            ("red", "Red"),
                            ("pink", "Pink"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("violet", "Violet"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                            ("gray", "Gray"),
                            ("multicolor", "Multicolor"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "transparency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transparent", "Transparent"),
                            ("semi_transparent", "Semi-transparent"),
                            ("translucent", "Translucent"),
                            ("opaque", "Opaque"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("heated", "Heated"),
                            ("oiled", "Oiled"),
                            ("dyed", "Dyed"),
                            ("irradiated", "Irradiated"),
                            ("fracture_filled", "Fracture filled"),
                            ("bleached", "Bleached"),
                            ("impregnated", "Impregnated"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "optic_character",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("isotropic", "Isotropic"),
                            ("uniaxial_positive", "Uniaxial (+)"),
                            ("uniaxial_negative", "Uniaxial (−)"),
                            ("biaxial_positive", "Biaxial (+)"),
                            ("biaxial_negative", "Biaxial (−)"),
                            ("aggregate", "Aggregate"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "refractive_index",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "specific_gravity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_polished", models.BooleanField(default=False)),
                ("conclusion", models.TextField(blank=True, default="")),
                ("is_finalized", models.BooleanField(default=False)),
                ("identified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.origin",
                    ),
                ),
                (
                    "shape_cut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.shapecut",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.species",
                    ),
                ),
                (
                    "stone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="orders.stone",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.variety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentUsed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("reading", models.CharField(blank=True, default="", max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.instrument",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments_used",
                        to="identification.identificationreport",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="identificationreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("report_number",),
                name="unique_active_report_number",
            ),
        ),
    ]
