# Generated by Django 5.2.17 on 2026-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="identificationreport",
            options={
                "permissions": [
                    ("finalize_report", "Can finalize an identification report")
                ]
            },
        ),
    ]
