# Generated by Django 5.2.17 on 2026-09-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_color"),
        ("identification", "0002_alter_identificationreport_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="identificationreport",
            name="dimensions",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="identificationreport",
            name="nature_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("natural", "Natural"),
                    ("synthetic", "Synthetic"),
                    ("treated", "Treated"),
                    ("enhanced", "Enhanced"),
                    ("artificial", "Artificial"),
                ],
                default="",
                max_length=20,
            ),
        ),
        # Color changes from a free-text choice to an FK lookup; the old text
        # values (e.g. "black") can't cast to a bigint, so drop and re-add the
        # column rather than alter it (dev data loss on color is acceptable).
        migrations.RemoveField(
            model_name="identificationreport",
            name="color",
        ),
        migrations.AddField(
            model_name="identificationreport",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.color",
            ),
        ),
        migrations.AlterField(
            model_name="identificationreport",
            name="optic_character",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sr", "SR — Singly refractive"),
                    ("adr", "ADR — Anomalous double refractive"),
                    ("dr", "DR — Double refractive"),
                    ("agg", "AGG — Aggregate"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="identificationreport",
            name="transparency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transparent", "Transparent"),
                    ("translucent", "Translucent"),
                    ("opaque", "Opaque"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
