# Generated by Django 5.2.17 on 2026-08-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("verify_user", "Can verify user"),
                    ("approve_user", "Can approve user"),
                ],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
