# Generated by Django 5.2.17 on 2026-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["-issued_at"],
                "permissions": [
                    ("issue_certificate", "Can issue a certificate"),
                    ("revoke_certificate", "Can revoke a certificate"),
                ],
            },
        ),
    ]
