# Generated by Django 5.2.17 on 2026-09-02 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_alter_certificate_options"),
        ("identification", "0003_identificationreport_dimensions_and_more"),
        ("orders", "0005_remove_order_unique_active_order_reference_no_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="certificate",
            name="unique_active_certificate_no",
        ),
        migrations.RenameField(
            model_name="certificate",
            old_name="certificate_no",
            new_name="certificate_number",
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("certificate_number",),
                name="unique_active_certificate_number",
            ),
        ),
    ]
