# Generated by Django 5.2.17 on 2026-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_payment_options_remove_payment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="status_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
