# Generated by Django 5.2.17 on 2026-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_bill_status_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={
                "ordering": ["-created_at"],
                "permissions": [("generate_bill", "Can generate a bill")],
            },
        ),
    ]
