# Generated by Django 5.2.17 on 2026-09-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_bill_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billitem",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
