# Generated by Django 5.2.17 on 2026-09-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_billitem_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="gepg_submitted",
            new_name="is_gepg_submitted",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="processed",
            new_name="is_processed",
        ),
    ]
