# Generated by Django 5.2.17 on 2026-09-01 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stoneprice",
            name="unique_active_price_per_stone_type",
        ),
        migrations.RemoveField(
            model_name="stoneprice",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="stoneprice",
            name="price_per_unit",
        ),
        migrations.RemoveField(
            model_name="stoneprice",
            name="unit",
        ),
        migrations.AddField(
            model_name="stoneprice",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stoneprice",
            name="stone_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price",
                to="core.stonetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="stoneprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("stone_type",),
                name="unique_price_per_stone_type",
            ),
        ),
    ]
